### ISSUE TITLE
The small group tab should not be visible to developers not in one

### ISSUE THREAD

**Issue by kmcnellis** [rcos/Observatory3#255]
The api call `<li ng-show="isLoggedIn() && (isMentor() || hasSmallGroup())"><a ng-href='/smallgroup'>Small Group</a></li>
` does not seem to sufficiently prevent this

**Comment by kmcnellis** [comment]
The error I'm getting (for a mentor) is specifically:
  var responseObject = smallgroup.toObject();
                                       ^
TypeError: Cannot read property 'toObject' of null
    at Promise.<anonymous> (/Users/kiana/dev/Observatory3/server/api/smallgroup/smallgroup.controller.js:59:40)

It shows the page but crashes the server.

**Comment by kmcnellis** [comment]
For a student:
/Users/kiana/dev/Observatory3/server/api/smallgroup/smallgroup.controller.js:102
        smallgroup.students.forEach(function(studentId){
                  ^
TypeError: Cannot read property 'students' of null
    at Promise.<anonymous> (/Users/kiana/dev/Observatory3/server/api/smallgroup/smallgroup.controller.js:102:19)

**Comment by kmcnellis** [comment]
Related to #354
